version: '2'
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - '8877:8877'
    links:
      - mongo
    command: npm start 
  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'

    
